### ISSUE TITLE
Addon does not working after HA update

### ISSUE THREAD

**Issue by m4rk89** [Hypfer/ICantBelieveItsNotValetudo#19]
Hello,

Unfortunately I have updated HomeAssistant to the latest 0.105.3 version and the addon does not working (it was working before the update !!!).

The problem is that the picture does not shown on the URL (http://192.168.XXX.XXX:3000/api/map/image and the port 3000 is not open on my Pi.

This is my config:
```
identifier: rockrobo
topicPrefix: valetudo
autoconfPrefix: homeassistant
broker_url: 'mqtt://XXX:XXX@192.168.XXX.XXX'
caPath: ''
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  border: 2
  scale: 4
mapDataTopic: valetudo/rockrobo/map_data
minMillisecondsBetweenMapUpdates: 10000
publishMapImage: true
webserver.enabled: true
```

My log:
```
[23:12:08] INFO: Setup config
[23:12:08] INFO: Start ICantVelieveItsNotValetudo
> i-cant-believe-its-not-valetudo@0.2.0 start /app
> node app.js
Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
Connected to MQTT Broker
```

The vacuum (Roborock S50, 1886 fimware, 0.4.0 valetudo) is successfully connected to the MQTT broker:
```
Loading configuration file: /mnt/data/valetudo/config.json
Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
Webserver running on port 80
Connected successfully to mqtt server
Robot connected
```

System log:
`20-02-14 23:50:42 WARNING (MainThread) [hassio.addons.validate] Unknown options webserver.enabled
`

Could you help me with this issue?
I have checked the host (rpi 4, hass.io) and the port 3000 is not open.
