### ISSUE TITLE
hosting the underlay image

### ISSUE THREAD

**Issue by brunoamaral** [Hypfer/ICantBelieveItsNotValetudo#23]
I was trying to setup the underlay image by hosting it inside the container, at /app/assets/img.

But it's not working. Is it supposed to be hosted outside of the container somehow?

```yaml 
{
  "mqtt": {
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://192.168.XX.XX",
    "caPath": "",
    "mapSettings": {
      "drawPath": true,
      "drawCharger": true,
      "drawRobot": true,
      "border": 2,
      "scale": 4,
      "underlay_path": "/app/assets/img/home_2d_reverse.png",
      "underlay_scale": 2,
      "underlay_x": 0,
      "underlay_y": 0
    },
    "mapDataTopic": "valetudo/rockrobo/map_data",
    "minMillisecondsBetweenMapUpdates": 250,
    "publishMapImage": true
  },
  "webserver": {
    "enabled": true,
    "port": 3030
  }
}
```
