### ISSUE TITLE
map/image not found

### ISSUE THREAD

**Issue by ufulu** [Hypfer/ICantBelieveItsNotValetudo#6]
I think I am missing a piece of the puzzle and hope you guys can help me: 

My Roborock Gen2 sports FW v11_001748 with Valetudo Beta 0.3.0 which works as expected. 

I run ICantBelieveItsNotValetudo in a docker container which reports: 

```
Webserver running on port 3000
connected to MQTT broker
```

my config.json is as follows: 

```
{
  "mqtt": {
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://192.168.39.31",
    "caPath": "",
    "mapSettings": {
      "drawPath": true,
      "drawCharger": true,
      "drawRobot": true,
      "border": 2,
      "scale": 4
    },
    "mapDataTopic": "valetudo/rockrobo/map_data",
    "minMillisecondsBetweenMapUpdates": 10000,
    "publishMapImage": true
  },
  "webserver": {
    "enabled": true,
    "port": 3000
  }
}
```

When I open the URL http://192.168.39.24:3000/api/map/image in a browser I get: 

`Not found
`
When I try to open http://192.168.39.24:3000 i get: 

`Cannot GET /`

Are there any further confiuration steps I missed so that ICantBelieveItsNotValetudo can display the map images? What is caPath? Or how do i get the images so that I can display them in HomeAssistant? 

In the past I had the following setup in HomeAssistant and the map displayed just fine. 

```
  - platform: rest
    resource: http://192.168.39.51/api/remote/map
    name: lisamap
    value_template: '{{ value_json.mapsrc }}'
```

```
camera:
  - platform: generic
    name: Vacuum Map
    still_image_url: http://192.168.39.51{{states.sensor.lisamap.state | string }}
    content_type: image/png
    framerate: 1
```

I really would appreciate some guidance thanks in advacne for your support!
