### ISSUE TITLE
How to install it via Docker 

### ISSUE THREAD

**Issue by sca075** [Hypfer/ICantBelieveItsNotValetudo#88]
I followed the instruction:
1) Can not find the docker package with docker pull.
2) docker compose do not work with the provided script.

Honestly.. really not well explained the how to.. install and use this package.

**Comment by Judman** [comment]
Any luck? I cannot get this to work with docker compose v2.

docker compose up and docker compose build give the same error "validating /home/judson/test/compose.yaml: (root) Additional property icantbelieveitsnotvaletudo is not allowed"

Docker version 24.0.2, build cb74dfc
Docker Compose version v2.18.1

Yaml - 

```
 icantbelieveitsnotvaletudo:
    build:
      context: ./ICantBelieveItsNotValetudo/
      dockerfile: Dockerfile
    container_name: "ICantBelieveItsNotValetudo"
    restart: always
    volumes:
      - /home/judson/test/config.json:/app/config.json
```
